### ISSUE TITLE
Add extra emails to mailchimp

### ISSUE THREAD

**Issue by moorepants** [moorepants/icsc2017.ucdavis.edu#20]
- [x] The extra ones Lucca sent.
- [x] do a google scholar search for emails (start with citations to city cycling)
- [x] Add Davis and Sacramento people related to bicycling.
  - [x] SABA
  - [x] City bike/ped coordinators
  - [x] City council/mayor
  - [x] Davis bike club
  - [x] Davis bicycles!

**Comment by moorepants** [comment]
@raliang This is one item for you to start with.

**Comment by raliang** [comment]
@moorepants Mind if I create a Google Sheet in the ICSC folder listing potential emails to add so you can check them?

**Comment by moorepants** [comment]
Yes, you can then import the emails to mailchimp after you get them together.

**Comment by raliang** [comment]
@moorepants at the moment, I have 25 emails compiled in the Sheet labeled "Emails". Can you please check them for me if you have time? Or should I just add them all in now?

**Comment by moorepants** [comment]
If you found them on academic papers that are about bicycling, just add them. I don't need to review.

**Comment by moorepants** [comment]
Ok, let's call this done. Thanks @raliang!
