### ISSUE TITLE
Create a how to get here page

### ISSUE THREAD

**Issue by moorepants** [moorepants/icsc2017.ucdavis.edu#23]
There are a number of pages on the Davis Wiki that already explain how to get here: https://localwiki.org. Point to them and glean the main info to add to our website.

**Comment by moorepants** [comment]
@raliang This is the page I'd like you to work on.

**Comment by raliang** [comment]
Added some maps for the Yolobus and driving. I'll need to write up the driving instructions. Also going to include a section for ride-share programs, like Uber and Lyft if that is ok.

**Comment by raliang** [comment]
@moorepants I have finished setting up the how to get here page. Do you mind checking it when you have time? Can you also tell me if the links for the maps work?

**Comment by moorepants** [comment]
I'll have time tomorrow to review a number of things. Sorry to be slow on this. Thank you.

**Comment by moorepants** [comment]
Rayming, the page looks great. I've published it and it is live on the website. Thanks.
