### ISSUE TITLE
Update the Committees page

### ISSUE THREAD

**Issue by moorepants** [moorepants/icsc2017.ucdavis.edu#26]
See: http://icsc2017.ucdavis.edu/committees/

- [x] Collect photos from the steering committee and create a nice table with their information (like the organizing committee.
- [x] Find out who are going to be on the scientific committee from Mont and create a third committee section with a table with their info. Some will be repeats of: https://events.unibo.it/icsc2016/scientific-committee
- [x] Add a section to recognize the student volunteers and other organizers.
- [x] Either randomize or ABC order the scientific committee.
- [x] The list is super long now, it might look better as a two column table.
- [x] Correct photos of Kelsie and Rayming

**Comment by moorepants** [comment]
@abemckay Can you take this issue?

**Comment by monthubbard** [comment]
Yes.

**Comment by moorepants** [comment]
Mont, I'm going to have the student Abe do this one.

**Comment by abemckay** [comment]
Yes, I can take on this issue, #26. I am planning on searching online for the email addresses of each person on the steering committee, but if either of you already have their emails available and could send them to me, that would work too. (Stefanie de Hair-Bujissen, Marco Dozza, Arend Schwab, Divera Twisk, Luca Pietrantoni, Heiko Johanssen, Otte Dietmar MHH)

@monthubbard do you know who will be on the scientific committee? If so I can work on getting their section set up as well.

**Comment by monthubbard** [comment]
Abe;

All the steering committee email addresses are on the committee page for the last ICSC

https://events.unibo.it/icsc2016/scientific-committee

I sent out the requests for the scientific committee yesterday and have received replies from about half. Let's give it another day or two and I'll supply you with all the names then. About half are from the last committee (the page in the link above) and half are new from the USA.

Mont

**Comment by moorepants** [comment]
Abe, the steering committee emails are here: http://cyclingsafety.net/committees.php. Note that we should not post their emails on our website, but post their photos and affiliations as we have for the existing organizing committee.

**Comment by abemckay** [comment]
Thanks. I also see that we already have a photo of each of them, from last year's website. If either of you think I should, I could still email each of them and ask if they have another image they would prefer. 

Mont, sounds good. I'll wait to hear from you.

**Comment by moorepants** [comment]
You can use the last year photo. Luca gave me permission to use content from that website. They will email us if they want it changed.

**Comment by monthubbard** [comment]
I asked them all in the sci com invitation whether it is OK to use last year's photo. Everyone so far has said yes.
Mont

**Comment by abemckay** [comment]
Great, thank you Jason and Mont! I'll use last years photos.

**Comment by abemckay** [comment]
Hey Mont, did you hear back from people about the scientific committee?

**Comment by monthubbard** [comment]
Abe;

Attached is a list of the Scientific recruitment status as of Jan 19. There are 47 people on the list.

Almost all the 2016 Committee re-upped (only 3 said no). Two (Luca and Stefanie) haven't responded but they're pretty sure since they are on the present steering committee. These are all from Europe and you already have their photos and affiliations. I would put these up first (now).

The second half (from USA mostly) only has 1 no but 8 have yet to respond.
You can put their names up (of the yeses) but I think we should contact them to ask for photos(see below). This will be more efficiently be done perhaps in a few days with a bulk email after more have responded (I sent a reminder email to them on Jan 17).

Also attached is an attendee list for a recent Spotlight bike/ped safety conference in Washington last month. Most of the USA Sci Comm are on this list but the affiliation will be only the organization and not contain the detailed section within the organization. Can you please look up on the web their more detailed affiliation and add this to their entry on the page so that all Committee members have detailed affiliations?

Maybe next week we can send them a blanket email explaining that you are composing and fleshing out (literally!) the page, asking for their photo and referring them to the already existing page where there are lots of photos but not theirs even though their name will be (this should motivate them to send the photo).

Thanks so much for helping with this.

Mont

**Comment by abemckay** [comment]
Mont, thanks for the details. I can try to get this list up this morning, except I am having trouble finding the attached lists. I don't see an attachment on github or through my email notice. 
Sorry to ask more from you, but could you resend the lists to me? You could try emailing me directly (mckayabe@gmail.com) or upload the list to the google drive (the "potential" list is [here](https://docs.google.com/spreadsheets/d/1TodtsKvMQnqvPMmuj2Zmh3HghoDGCJBAQwihmauy8D8/edit#gid=0)) or use a better way I haven't though of.  Sorry for the delay.

**Comment by monthubbard** [comment]
Abe;

Sorry I didn't realize that the attached lists wouldn't make it through. I have emailed them to you directly.

Mont

**Comment by abemckay** [comment]
Got 'em. Thanks Mont!

**Comment by abemckay** [comment]
Should I post their full name and title? For example, last year's site shows "Dr M. Dozza" and our excel list says "Marco Dozza". Should I follow one of those conventions or combine for full details "Dr Marco Dozza?"

**Comment by moorepants** [comment]
I would follow what they did last year. The Europeans have different cultural traditions that we could be breaking if we format them like we want.

**Comment by abemckay** [comment]
Roger that. Thanks Jason.
For the Americans, (which will be new) I'll try to put their full title and name?

**Comment by moorepants** [comment]
Yes, you can copy how the organizing committee was done.

**Comment by abemckay** [comment]
I have completed the scientific committee list, with pictures of the Europeans. I searched around for the details of the Americans and added those as well. Two people (Peter Jacobsen & Rebecca Sanders) were not on the Spotlight list, so I did not have their organization. I didn't want to get the wrong Peter Jacobsen's info, so I left their details blank. Let me know if you would like me to make any changes or add detail, but I will most likely not be able to get to it till next Friday.

**Comment by monthubbard** [comment]
Abe;

Two more yeses from the second half of the Sci Com list.

Eva Heinen
Lisa Aultman-Hall.

**Comment by monthubbard** [comment]
I like the informality of just the name but Jason and Deb may differ.

**Comment by monthubbard** [comment]
Abe;

Fast work!

A few minor tidy-ups.

Rowangould doesn't have  a hyphen.
Here's Peter Jacobsen's Linked in url with a photo.
https://www.linkedin.com/in/peter-jacobsen-aa747a41

Rebecca Sanders is with Toole Design with photo.
https://www.linkedin.com/in/rebecca-sanders-69169b4
<https://www.google.com/search?q=rowangould+UNM&oq=rowangould+UNM&aqs=chrome..69i57.4668j0j7&sourceid=chrome&ie=UTF-8#>

  1.  <https://www.google.com/search?biw=951&bih=1002&q=related:https://www.linkedin.com/in/rebecca-sanders-69169b4+Rebecca+Sanders+Toole+Design&tbo=1&sa=X&ved=0ahUKEwjhnefbo9LRAhWnhFQKHYcdA60QHwgrMAI>

Actually I think it's OK to use a photo for anyone from their Linked In page. Probably almost all will have.

Mont

**Comment by abemckay** [comment]
Thanks Mont. 
I've fixed "Rowangould" and added descriptions for the two missing ones. I'll be able to get to the pictures and new committee members on Friday.

**Comment by abemckay** [comment]
Okay, I believe this task is completed. Let me know if there are more additions to the committee, or if you see any needed edits!

**Comment by moorepants** [comment]
Awesome, it looks great. Only issue...is that Rayming? Doesn't quite look like him to me.

**Comment by abemckay** [comment]
Oh my, it may not be. I did some internet searching at put up my best guess. (I thought I could be a bit bolder with guessing with my fellow students.) When I put the section up, I emailed the other volunteers, asking if they wanted to change their pictures. Rayming will probably update me soon.

**Comment by monthubbard** [comment]
Abe;

Would it make sense to list the americans alphabetically or even interleave them with the Europeans?

Mont

**Comment by moorepants** [comment]
I agree with Mont that abc order or at least interleaving them would be preferable.

**Comment by monthubbard** [comment]
I think the Europeans are already alphabetical.

**Comment by abemckay** [comment]
Okay, the Scientific Committee is A to Z. I was having trouble getting the pictures to size correctly when trying a 2 column table. I'm going to work on the other page now, but will come back to making the 2 columns when I finish.

**Comment by moorepants** [comment]
@abemckay Thanks. Also make sure to get correct photos from Kelsie @krnebreda and Rayming @raliang.

**Comment by moorepants** [comment]
I'll have a look at the two column issue right now.

**Comment by monthubbard** [comment]
Abe;

Some minor changes to the Scientific Committee list

3 new additions:

Tara Goddard   Nohad Toulan School of Urban Studies & Planning  Portland State University
Elliot Martin Transportation Sustainability Research Center   UC Berkeley
Noreen McDonald   Associate Professor, Department of City and Regional Planning, University of North Carolina, Chapel Hill


One (Rowangould) presently out of order

Thanks for making these changes.

Mont

**Comment by abemckay** [comment]
Okay, the three new members are added, and the ordering if fixed around Rowangould (good spotting, Mont!). Kelsie sent me an updated picture, but still waiting for Rayming. 
Let me know if you see anything else!

**Comment by monthubbard** [comment]
Thanks Abe.

On Feb 10, 2017, at 10:56 AM, abemckay <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, the three new members are added, and the ordering if fixed around Rowangould (good spotting, Mont!). Kelsie sent me an updated picture, but still waiting for Rayming.
Let me know if you see anything else!
