### ISSUE TITLE
Make the site faster

### ISSUE THREAD

**Issue by moorepants** [moorepants/icsc2017.ucdavis.edu#29]
Some things that are slow:

- [x] Reduce size of front page images
- [ ] Google maps
- [ ] Dreamhost shared server just seems to be slow, but I've had faster WP sites in the past.\
- [x] Get increased memory on server from dreamhost.
- [x] The mysql database and the website files were on servers in CA and VA, now they are all on the CA server. This should speed things up.

Useful sites to check speed:

- https://developers.google.com/speed/pagespeed/insights/
- https://tools.pingdom.com

**Comment by moorepants** [comment]
Couple of graphs form pindgom. First is from San Jose (~10 s):
![selection_142](https://cloud.githubusercontent.com/assets/276007/22602374/ca6256e4-e9f7-11e6-8772-5154927048c7.jpg)

And Stockholm (~23 s):
![selection_141](https://cloud.githubusercontent.com/assets/276007/22602377/d22438f2-e9f7-11e6-8723-7feacc7d5371.jpg)

It seems like the server response is the vast majority. Loading the assets isn't a big deal. I see some evidence in forums that this is due to Dreamhost's slow MySQL server.

**Comment by monthubbard** [comment]
Maybe we could get a new host. This is really a big problem. Could UC Davis host it?
Mont

**Comment by moorepants** [comment]
I can do an upgrade on the same host that will cost us $17 a month for the next year. This would improve it, but I'd need to ask support. I already have a support request in.

**Comment by monthubbard** [comment]
Isn't it legitimate for UCD to host it? For free?

**Comment by moorepants** [comment]
No, because they will not permit any custom installations of Wordpress. For example, they wouldn't support the theme I bought or any of the plugins we are using. They may be willing to support that but we'd have to pay a UCD web developer to manage it. The reason I went with my server is because I'm doing the web development for free and we don't have to ask someone else to make changes on the website anytime we need anything changed. UCD will give you a free Wordpress site but they don't let you turn on any features or install anything. It is effectively useless. I could inquire but it would likely be much simpler and cost less if we just upgraded what I have going.

**Comment by moorepants** [comment]
Some notes from Dreamhost support:

> your user's processes are being killed for going over the shared server memory limit, can't tell which site it is because they are all under the same user, but i did see premature end of script errors on both icsc2017.ucdavis.edu and moorepants.info's logs. my suggestion here before you try upgrading is moving each domain to it's own user, that will allocate a little more of the shared server resources. you can also increase these resources a bit for each user, so i suggest you try those things first, but yes, the processes are being killed for going over the shared memory limit and that will slow it down https://help.dreamhost.com/hc/en-us/articles/214200688-php-ini-overview https://help.dreamhost.com/hc/en-us/articles/214893937-How-do-I-increase-the-PHP-memory-limit-

They also increased the memory limit for my main user, which may fix things.

**Comment by moorepants** [comment]
The increase they made to the user's memory has significantly sped it up for me. I'm getting 1.5 second load times instead of 10+ seconds. Let me know if it seems better for you all.

**Comment by monthubbard** [comment]
Much better.

**Comment by moorepants** [comment]
Dreamhost (the service provider) helped me fix one more issue. For some reason my main website files were on a west coast data center and the database was on an east coast data center. This also contributed to the speed. They have now migrated the database to the west coast datacenter and I'm getting really great load times. I'm closing this issue as solved.
