### ISSUE TITLE
Improvements to the venue page

### ISSUE THREAD

**Issue by moorepants** [moorepants/icsc2017.ucdavis.edu#30]
- [x] Add info about conference center and neighboring buildings (mondavi, museum, arboretum)
- [x] Add the hotels that will be available to stay at (Hyatt and check on hallmark)
- [x] Include some tourist attractions in Davis
- [x] Include tourist attractions in surrounding area (Sacramento, etc)
- [x] Include basic info about nearby destinations (SF, Napa, Tahoe, Yosemite, etc)
- [x] Add link to Davis bike map.
- [x] Add more prominent link to the Davis Wiki.
- [x] Include the USBHoF as the Friday night dinner location. Mention the museum and the Hall of fame. There will be a special exhibit on highwheelers there that week.

**Comment by moorepants** [comment]
@abemckay Can you work on this issue? If so, assign yourself.

**Comment by abemckay** [comment]
Jason, I won't be abel to get to it till next Friday, and then I think it'll take me at least a week to finish.  If that's okay, then I can take it.

**Comment by moorepants** [comment]
Ok, I'll assign you now. If one of the other students frees up before then I'll add them.

**Comment by moorepants** [comment]
Looks great. Closing.
