### ISSUE TITLE
Role problems with wpabstracts

### ISSUE THREAD

**Issue by moorepants** [moorepants/icsc2017.ucdavis.edu#31]
wpabstracts takes over the subscriber and editor roles and if you set the settings such that these users can't log in via the backend, then if you have actual editors and subscribers, they can't log in.

**Comment by moorepants** [comment]
Note that wp abstracts makes "subscribers" be abstract authors/submitters and "editors" to be abstract reviewers.

**Comment by abemckay** [comment]
Jason, I tried logging in through the "Author or Reviewer" and "Administrator Login" links, through http://icsc2017.ucdavis.edu/wp-admin.php and http://icsc2017.ucdavis.edu/wp-login.php. All of them brought me back to the front end. Dang

**Comment by moorepants** [comment]
Is it still not working? I changed your roles from "editor" to "author" to see if that works.

**Comment by abemckay** [comment]
Jason, now that you switched my setting to Administrator, I can see the dashboard. (thumbs up)

**Comment by moorepants** [comment]
Ok. I've email the author of wp abstracts and see if there is a better workaround for the future.

**Comment by moorepants** [comment]
Closing this. We are just giving everyone admin roles. The developer of the plugin said a future version may be different.
