### ISSUE TITLE
Uncover the NCST link on the sponsor's page

### ISSUE THREAD

**Issue by monthubbard** [moorepants/icsc2017.ucdavis.edu#40]

**Comment by moorepants** [comment]
This can be fixed by increasing the sponsor logo image size or reducing the text in the box.

**Comment by moorepants** [comment]
This is now fixed for me. Please check on your computer to confirm.

**Comment by monthubbard** [comment]
Fixed.


On Feb 14, 2017, at 8:35 AM, Jason K. Moore <notifications@github.com<mailto:notifications@github.com>> wrote:


This is now fixed for me. Please check on your computer to confirm.
