### ISSUE TITLE
Improvements to committee images

### ISSUE THREAD

**Issue by moorepants** [moorepants/icsc2017.ucdavis.edu#41]
Note from a steering committee member:

> Today I visited the ICSC2017 website, the committee part of the website. In my explorer the pictures of the committee members shown here are unequally sized. Could you please check if this is the case on your pc as well. Could you please improve the appearance? Thanks in advance.

I've asked for a screenshot of what they see and the exact browser and version. This may be an IE compatibility issue.

Some things:

- [x] Upload all the committee member images to our site instead of linking to them on other sites.
- [x] Scale all images to the same aspect ratio, reduce the size to 100-150 pixels wide, and save as 50-75% quality jpgs for small file size. (the scientific committee images should be less wide than the other lists)

**Comment by moorepants** [comment]
@abemckay FYI, here is some info for the image issue. Note this is low priority.

**Comment by moorepants** [comment]
Also here is the page load speed tool: https://tools.pingdom.com/

**Comment by moorepants** [comment]
@abemckay Here are some screenshots from: "I used internet explorer under windows 10"
![image003](https://cloud.githubusercontent.com/assets/276007/22930925/6979d824-f277-11e6-8645-4750edfc0895.jpg)
![image002](https://cloud.githubusercontent.com/assets/276007/22930928/6be397f8-f277-11e6-8b0c-2dc583e162a9.png)

I didn't realize that it was this bad. Internet explorer is notorious for not following the same rendering standards as the other major browsers. The method I described yesterday to crop, scale, and export at lower jpg quality would help deal with this. I'm removing the low priority tag. We should fix this.

**Comment by abemckay** [comment]
Okay, I downloaded, adjusted the aspect ratio, resized, and then uploaded all the images for the scientific committee and students. 
One issue; C. Woolsgrove's picture is now really fuzzy (it was quite wide, so the aspect ratio zoomed in). I didn't find any other pictures of him on the web. Do you think 1) leave it blurry, 2) leave it a different size, or 3) try to get a different picture?

**Comment by moorepants** [comment]
Maybe just ask him for a better picture.

**Comment by moorepants** [comment]
Abe, this all looks great. Next time you are on a computer with Windows can you double check that this is fixed in internet explorer and/or edge.

I'm closing this. Thanks!

**Comment by abemckay** [comment]
Jason,
On 'edge', the organizing committee's images are still larger. I thought they looked good, so I didn't try to change them. All the other images are a uniform size. Hopefully you can see them in the screen snips below. 
![image](https://cloud.githubusercontent.com/assets/25090408/23806408/684bb7d0-0576-11e7-858b-5ad0d8015ebb.png)
![image](https://cloud.githubusercontent.com/assets/25090408/23806435/888cc908-0576-11e7-9e3e-9f0632338cff.png)

**Comment by moorepants** [comment]
Can you fix the organizing committee ones too?

**Comment by abemckay** [comment]
Certainly, the organizing committee now has the same size images! Sorry to make you re-open the issue. 
From edge:
![image](https://cloud.githubusercontent.com/assets/25090408/23810947/9a75e6e2-0588-11e7-8d56-a363ee588227.png)

**Comment by moorepants** [comment]
Great! We're done here.
