### ISSUE TITLE
Why do some abstracts trip the UCD spam filter?

### ISSUE THREAD

**Issue by monthubbard** [moorepants/icsc2017.ucdavis.edu#42]
From: 2017 International Cycling Safety Conference <icsc2017@ucdavis.edu>
Subject: New Abstract Submitted
Date: February 10, 2017 at 3:25:13 PM PST
To: <mhubbard@ucdavis.edu>

Hello Mont Hubbard,

You have a new abstract for 2017 International Cycling Safety Conference
Abstract Title: Longitudinal Rumble Strips Require a Safety Compromise for Bicycles Versus Motor Vehicles
Abstract ID: 5

Regards,

ICSC 2017 Organizing Committee
2017 International Cycling Safety Conference
http://icsc2017.ucdavis.edu

7.6/5.0
This incoming message has been identified by the UCD central filters as
possible spam.  This attachment is provided so that you can review the
reasons the message was tagged, and to assist with additional filtering
if you wish to supplement the central filters with your own local rules.

If you have further questions please email ithelp@ucdavis.edu for
assistance.

Content analysis details:   (7.6 points, 5.0 required)

pts rule name              description
---- ---------------------- --------------------------------------------------
3.5 BAYES_99               BODY: Bayes spam probability is 99 to 100%
                           [score: 0.9970]
0.5 RCVD_IN_SORBS_SPAM     RBL: SORBS: sender is a spam source
                           [66.33.200.130 listed in dnsbl.sorbs.net]
-0.0 RP_MATCHES_RCVD        Envelope sender domain matches handover relay domain
0.1 HTML_MESSAGE           BODY: HTML included in message
0.7 MIME_HTML_ONLY         BODY: Message only has text/html MIME parts
0.5 DCC_CHECK              Detected as bulk mail by DCC (dcc-servers.net)
0.1 DCC_REPUT_70_89        DCC reputation between 70 and 89 %
0.4 HTML_MIME_NO_HTML_TAG  HTML-only message, but there is no HTML tag
1.8 TO_NO_BRKTS_HTML_ONLY  To: lacks brackets and HTML only

**Comment by moorepants** [comment]
This is only a problem if the UCD spam filter were to actually block the message from getting to your inbox. As of now it is just "tagging" the message with a warning. The last lines show the reasons it thinks it is spam. The main reason seems to be that is scans the body content and it thinks it is spam. Not sure what we can do about that. It does look like spam.

**Comment by moorepants** [comment]
The only suggestion I have is for you to send to ithelp@ucdavis.edu with this information.

**Comment by moorepants** [comment]
Another option is to change your email address in your profile on the website to your gmail address. Then the email never goes through UCD servers, so you won't get the warning.

**Comment by moorepants** [comment]
i looked into this, but didn't really get a suitable solution from UCD folks. Seems like this is something that they can't change for us. We have to make our emails such that it doesn't look like spam to UCD, which isn't that clear how to do. Closing.
