### ISSUE TITLE
Invite self-driving car bicyclists detection algorithm researchers

### ISSUE THREAD

**Issue by moorepants** [moorepants/icsc2017.ucdavis.edu#43]
- [x] Ford (Jason contacted two different people)
- [ ] Google (who wrote this report: https://static.googleusercontent.com/media/www.google.com/en//selfdrivingcar/files/reports/report-0616.pdf?)
- [ ] Uber
- [x] Researchers from this article: http://spectrum.ieee.org/cars-that-think/transportation/self-driving/the-selfdriving-cars-bicycle-problem
- [ ] Waymo (http://spectrum.ieee.org/cars-that-think/transportation/self-driving/waymo-shows-off-its-doityourself-robocar-hardware)
- [ ] Volvo (https://www.media.volvocars.com/ca/fr-ca/media/pressreleases/48219)

**Comment by kngissah** [comment]
The group that wrote the Google report turned into/became a part of Waymo as far as I know.

**Comment by moorepants** [comment]
Thanks for that. I'll try to invite Waymo. I'll see if they have a public email address.

**Comment by moorepants** [comment]
We did what we could and got a few abstracts in this realm. Closing.
