### ISSUE TITLE
Add all important locations to the map on the front page

### ISSUE THREAD

**Issue by moorepants** [moorepants/icsc2017.ucdavis.edu#45]
There are a number of things listed on the venue page. These need to be added as "points of interest" so that they show up on the main map. This should have only the Davis locations.

Bicycle Related
- [x] Bike barn
- [x] Bike Collective
- [x] Bicycle tunnels
- [x] Bicycle stop lights
- [x] Dutch intersection
- [x] Bicycle circles
- [x] Other bike shops

Lodging
- [x] Hyatt
- [x] Hallmark
- [x] Best wester

Conference Locations
- [x] Bainer Hall
- [x] Kemper Hall
- [x] UCD Conference Center
- [x] USBHoF
- [x] Farmer's Market
- [x] Institute for Transportation Studies in West Village

Attractions
- [x] shretti art museum
- [x] Mondavi
- [x] arboretum
- [x] Bohart Bug Museum

**Comment by moorepants** [comment]
@raliang Would you like to work on this issue now?

**Comment by raliang** [comment]
I'll take a shot at it, but I'm not really sure how to add the points on the map. Mind if I come later today to talk to you about it?

**Comment by moorepants** [comment]
In the backend of the website you need to add "Points of Interest". You should also group them in into PIO groups like: Attractions, Hotels, Conference Related, etc. Here is what the new points of interest looks like:
![image](https://cloud.githubusercontent.com/assets/276007/23763832/14c0e0f2-04b0-11e7-8f96-803cdea4183a.png)

**Comment by moorepants** [comment]
@raliang I haven't seen any progress on this. Do you plan to complete this task?

**Comment by raliang** [comment]
@moorepants My bad. I do plan to complete this. I'll get on it

**Comment by raliang** [comment]
@moorepants I was just checking the POI on the page, and the lodging heading doesn't show up at the moment. Is this because I'm editing the points of interests, or is there something with the page?

**Comment by moorepants** [comment]
I don't quite understand what you are describing. But maybe you haven't published the POI Group?

**Comment by raliang** [comment]
ok it's fine now. Probably was because I hadn't published the POIs

**Comment by moorepants** [comment]
I just listed  bunch of items at the top of this thread that should be added.

**Comment by raliang** [comment]
I've added all the things on the list to the POI section. Anything I should do here?

**Comment by moorepants** [comment]
@raliang This looks good. Here are some comments from Mont:

> Jason;

Can you notify the correct person that several of the Points of Interest need changes?

1. The "Shretti" art museum is mis-labeled. It should be "Manetti Shrem" museum of art. Further, it is mis-located on the map.

2. ITS should be labelled as "Institute of Transportation Studies"

3. Bainer Hall should be added to show location of the other workshop. The present location of Kemper Hall is incorrect.  The ASUCD bike barn location is incorrect.

 Mondavi Center location (shown at the Silo) is incorrect.

I suspect Bohart would prefer to be more respectfully labelled Bohart Museum of Entomology

**Comment by raliang** [comment]
I think all the changes have been made. Was a bit confused about the Bainer Hall part, but I think it was simply a misplacement of the POI dot.

**Comment by moorepants** [comment]
Great work here!
