### ISSUE TITLE
Facebook buttons on front page don't seem to do anything

### ISSUE THREAD

**Issue by moorepants** [moorepants/icsc2017.ucdavis.edu#46]
@krnebreda do they work for you?

**Comment by moorepants** [comment]
Seems like the API keys are missing in the widget.

**Comment by krnebreda** [comment]
No, I can't seem to get the API keys to work. The event ID and link are correct though.

**Comment by moorepants** [comment]
So you pasted the API keys in? Or can't get them from Facebook? I don't see any pasted in the widget interface.

**Comment by moorepants** [comment]
@krnebreda It has bee two months and this is still broken. Do you plan to fix it? If not, please remove the widget.

**Comment by moorepants** [comment]
I removed this since it has never been fixed.
